package libssh

const (
	SSH2_MSG_DISCONNECT      = 1
	SSH2_MSG_IGNORE          = 2
	SSH2_MSG_UNIMPLEMENTED   = 3
	SSH2_MSG_DEBUG           = 4
	SSH2_MSG_SERVICE_REQUEST = 5
	SSH2_MSG_SERVICE_ACCEPT  = 6

	SSH2_MSG_KEXINIT = 20
	SSH2_MSG_NEWKEYS = 21

	SSH2_MSG_KEXDH_INIT     = 30
	SSH2_MSG_KEXDH_REPLY    = 31
	SSH2_MSG_KEX_ECDH_INIT  = 30
	SSH2_MSG_KEX_ECDH_REPLY = 31
	SSH2_MSG_ECMQV_INIT     = 30
	SSH2_MSG_ECMQV_REPLY    = 31

	SSH2_MSG_KEX_DH_GEX_REQUEST_OLD            = 30
	SSH2_MSG_KEX_DH_GEX_GROUP                  = 31
	SSH2_MSG_KEX_DH_GEX_INIT                   = 32
	SSH2_MSG_KEX_DH_GEX_REPLY                  = 33
	SSH2_MSG_KEX_DH_GEX_REQUEST                = 34
	SSH2_MSG_USERAUTH_REQUEST                  = 50
	SSH2_MSG_USERAUTH_FAILURE                  = 51
	SSH2_MSG_USERAUTH_SUCCESS                  = 52
	SSH2_MSG_USERAUTH_BANNER                   = 53
	SSH2_MSG_USERAUTH_PK_OK                    = 60
	SSH2_MSG_USERAUTH_PASSWD_CHANGEREQ         = 60
	SSH2_MSG_USERAUTH_INFO_REQUEST             = 60
	SSH2_MSG_USERAUTH_GSSAPI_RESPONSE          = 60
	SSH2_MSG_USERAUTH_INFO_RESPONSE            = 61
	SSH2_MSG_USERAUTH_GSSAPI_TOKEN             = 61
	SSH2_MSG_USERAUTH_GSSAPI_EXCHANGE_COMPLETE = 63
	SSH2_MSG_USERAUTH_GSSAPI_ERROR             = 64
	SSH2_MSG_USERAUTH_GSSAPI_ERRTOK            = 65
	SSH2_MSG_USERAUTH_GSSAPI_MIC               = 66

	SSH2_MSG_GLOBAL_REQUEST            = 80
	SSH2_MSG_REQUEST_SUCCESS           = 81
	SSH2_MSG_REQUEST_FAILURE           = 82
	SSH2_MSG_CHANNEL_OPEN              = 90
	SSH2_MSG_CHANNEL_OPEN_CONFIRMATION = 91
	SSH2_MSG_CHANNEL_OPEN_FAILURE      = 92
	SSH2_MSG_CHANNEL_WINDOW_ADJUST     = 93
	SSH2_MSG_CHANNEL_DATA              = 94
	SSH2_MSG_CHANNEL_EXTENDED_DATA     = 95
	SSH2_MSG_CHANNEL_EOF               = 96
	SSH2_MSG_CHANNEL_CLOSE             = 97
	SSH2_MSG_CHANNEL_REQUEST           = 98
	SSH2_MSG_CHANNEL_SUCCESS           = 99
	SSH2_MSG_CHANNEL_FAILURE           = 100

	SSH2_DISCONNECT_HOST_NOT_ALLOWED_TO_CONNECT    = 1
	SSH2_DISCONNECT_PROTOCOL_ERROR                 = 2
	SSH2_DISCONNECT_KEY_EXCHANGE_FAILED            = 3
	SSH2_DISCONNECT_HOST_AUTHENTICATION_FAILED     = 4
	SSH2_DISCONNECT_RESERVED                       = 4
	SSH2_DISCONNECT_MAC_ERROR                      = 5
	SSH2_DISCONNECT_COMPRESSION_ERROR              = 6
	SSH2_DISCONNECT_SERVICE_NOT_AVAILABLE          = 7
	SSH2_DISCONNECT_PROTOCOL_VERSION_NOT_SUPPORTED = 8
	SSH2_DISCONNECT_HOST_KEY_NOT_VERIFIABLE        = 9
	SSH2_DISCONNECT_CONNECTION_LOST                = 10
	SSH2_DISCONNECT_BY_APPLICATION                 = 11
	SSH2_DISCONNECT_TOO_MANY_CONNECTIONS           = 12
	SSH2_DISCONNECT_AUTH_CANCELLED_BY_USER         = 13
	SSH2_DISCONNECT_NO_MORE_AUTH_METHODS_AVAILABLE = 14
	SSH2_DISCONNECT_ILLEGAL_USER_NAME              = 15

	SSH2_OPEN_ADMINISTRATIVELY_PROHIBITED = 1
	SSH2_OPEN_CONNECT_FAILED              = 2
	SSH2_OPEN_UNKNOWN_CHANNEL_TYPE        = 3
	SSH2_OPEN_RESOURCE_SHORTAGE           = 4

	SSH2_EXTENDED_DATA_STDERR = 1
)
